# app/config/common/parameters.yml
parameters:
    #Database
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     null
    database_name:     symfony
    database_user:     root
    database_password: null
    #Mailer
    mailer_transport: smtp
    mailer_host:      127.0.0.1
    mailer_user:      null
    mailer_password:  null
    #Locale
    locale: en
    #Token
    secret: ThisTokenIsNotSoSecretChangeIt
