# AppBundle/Service/Meat/services.yml
services:
    goutte_client:
        class:     Goutte\Client

    collector:
        class:     AppBundle\Service\Meat\Collector
        arguments: [ "@doctrine.orm.entity_manager", "@goutte_client" ]

    detector:
        class:     AppBundle\Service\Meat\Detector
        arguments: [ "@request_stack" ]